// ============================================================
// Choice Properties — Config Generator
// Runs at build time to create config.js from environment vars
// Works with Cloudflare Pages, Netlify, or any CI/CD system
// Never edit config.js directly — edit this file instead
// ============================================================

const fs = require('fs');

// Read from environment variables (set in your hosting platform's dashboard)
const config = {
  SUPABASE_URL:      process.env.SUPABASE_URL      || '',
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || '',

  IMAGEKIT_URL:        process.env.IMAGEKIT_URL        || '',
  IMAGEKIT_PUBLIC_KEY: process.env.IMAGEKIT_PUBLIC_KEY || '',

  GEOAPIFY_API_KEY: process.env.GEOAPIFY_API_KEY || '',

  COMPANY_NAME:     process.env.COMPANY_NAME     || 'Choice Properties',
  COMPANY_EMAIL:    process.env.COMPANY_EMAIL    || '',
  COMPANY_PHONE:    process.env.COMPANY_PHONE    || '',
  COMPANY_TAGLINE:  process.env.COMPANY_TAGLINE  || 'Your trust is our standard.',
  COMPANY_ADDRESS:  process.env.COMPANY_ADDRESS  || '',

  ADMIN_EMAILS: (process.env.ADMIN_EMAILS || '').split(',').map(e => e.trim()).filter(Boolean),

  LEASE_DEFAULT_LATE_FEE_FLAT:  Number(process.env.LEASE_DEFAULT_LATE_FEE_FLAT)  || 50,
  LEASE_DEFAULT_LATE_FEE_DAILY: Number(process.env.LEASE_DEFAULT_LATE_FEE_DAILY) || 10,
  LEASE_DEFAULT_EXPIRY_DAYS:    Number(process.env.LEASE_DEFAULT_EXPIRY_DAYS)    || 7,

  FEATURES: {
    CO_APPLICANT:    process.env.FEATURE_CO_APPLICANT    !== 'false',
    VEHICLE_INFO:    process.env.FEATURE_VEHICLE_INFO    !== 'false',
    DOCUMENT_UPLOAD: process.env.FEATURE_DOCUMENT_UPLOAD !== 'false',
    MESSAGING:       process.env.FEATURE_MESSAGING       !== 'false',
    REALTIME_UPDATES:process.env.FEATURE_REALTIME_UPDATES !== 'false',
  },
};

// Validate required values
const required = ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'IMAGEKIT_URL', 'IMAGEKIT_PUBLIC_KEY'];
const missing  = required.filter(k => !config[k]);
if (missing.length) {
  console.error('❌ Missing required environment variables:', missing.join(', '));
  console.error('   Set these in your hosting platform\'s environment variables dashboard');
  process.exit(1);
}

if (!config.GEOAPIFY_API_KEY) {
  console.warn('⚠  GEOAPIFY_API_KEY is not set — address autocomplete will be disabled');
}

// Generate config.js
const output = `// ============================================================
// Choice Properties — Auto-generated config
// Generated by generate-config.js at build time
// DO NOT EDIT THIS FILE — it is overwritten on every deploy
// Edit environment variables in your hosting platform dashboard
// ============================================================

const CONFIG = {
  SUPABASE_URL:      '${config.SUPABASE_URL}',
  SUPABASE_ANON_KEY: '${config.SUPABASE_ANON_KEY}',

  IMAGEKIT_URL:        '${config.IMAGEKIT_URL}',
  IMAGEKIT_PUBLIC_KEY: '${config.IMAGEKIT_PUBLIC_KEY}',

  GEOAPIFY_API_KEY: '${config.GEOAPIFY_API_KEY}',

  COMPANY_NAME:     '${config.COMPANY_NAME}',
  COMPANY_EMAIL:    '${config.COMPANY_EMAIL}',
  COMPANY_PHONE:    '${config.COMPANY_PHONE}',
  COMPANY_TAGLINE:  '${config.COMPANY_TAGLINE}',
  COMPANY_ADDRESS:  '${config.COMPANY_ADDRESS}',

  ADMIN_EMAILS: ${JSON.stringify(config.ADMIN_EMAILS)},

  LEASE_DEFAULT_LATE_FEE_FLAT:  ${config.LEASE_DEFAULT_LATE_FEE_FLAT},
  LEASE_DEFAULT_LATE_FEE_DAILY: ${config.LEASE_DEFAULT_LATE_FEE_DAILY},
  LEASE_DEFAULT_EXPIRY_DAYS:    ${config.LEASE_DEFAULT_EXPIRY_DAYS},

  FEATURES: {
    CO_APPLICANT:     ${config.FEATURES.CO_APPLICANT},
    VEHICLE_INFO:     ${config.FEATURES.VEHICLE_INFO},
    DOCUMENT_UPLOAD:  ${config.FEATURES.DOCUMENT_UPLOAD},
    MESSAGING:        ${config.FEATURES.MESSAGING},
    REALTIME_UPDATES: ${config.FEATURES.REALTIME_UPDATES},
  },
};

// Derived helpers
CONFIG.isLocalhost = ['localhost', '127.0.0.1'].includes(location.hostname);
CONFIG.baseUrl     = location.origin;

// ImageKit delivery helper
CONFIG.img = function(url, preset) {
  const fallback = url || '/assets/placeholder-property.jpg';
  if (!url) return '/assets/placeholder-property.jpg';
  if (!CONFIG.IMAGEKIT_URL || CONFIG.IMAGEKIT_URL.includes('YOUR_IMAGEKIT_ID')) {
    return fallback;
  }
  const transforms = {
    card:      'tr:w-600,q-80,f-webp',
    gallery:   'tr:w-1200,q-90,f-webp',
    thumb:     'tr:w-120,h-120,c-maintain_ratio,q-75,f-webp',
    lightbox:  'tr:q-95,f-webp',
    og:        'tr:w-1200,h-630,c-force,fo-center,q-85,f-webp',
    avatar:    'tr:w-80,h-80,c-force,fo-face,q-80,f-webp',
    avatar_lg: 'tr:w-160,h-160,c-force,fo-face,q-85,f-webp',
  };
  const tr = transforms[preset] || transforms.gallery;
  if (url.startsWith(CONFIG.IMAGEKIT_URL)) {
    const clean = url.replace(/\\/tr:[^/]+/, '');
    return clean.replace(CONFIG.IMAGEKIT_URL, \`\${CONFIG.IMAGEKIT_URL}/\${tr}\`);
  }
  return \`\${CONFIG.IMAGEKIT_URL}/\${tr}/\${encodeURIComponent(url)}\`;
};

Object.freeze(CONFIG);
Object.freeze(CONFIG.FEATURES);
`;

fs.writeFileSync('config.js', output);
console.log('✅ config.js generated successfully from environment variables');
