// Choice Properties — Static file server for Replit
// Serves static files and regenerates config.js from env vars on startup.

const http = require('http');
const fs   = require('fs');
const path = require('path');
const zlib = require('zlib');

// ── Regenerate config.js from Replit secrets ──────────────
const SUPABASE_URL      = (process.env.SUPABASE_URL      || '').replace(/\/$/, '');
const SUPABASE_ANON_KEY =  process.env.SUPABASE_ANON_KEY || '';

const configJs = `// Auto-generated by serve.js from Replit environment secrets
const CONFIG = {
  SUPABASE_URL:      '${SUPABASE_URL}',
  SUPABASE_ANON_KEY: '${SUPABASE_ANON_KEY}',

  IMAGEKIT_URL:        '${process.env.IMAGEKIT_URL        || ''}',
  IMAGEKIT_PUBLIC_KEY: '${process.env.IMAGEKIT_PUBLIC_KEY || ''}',

  GEOAPIFY_API_KEY: '${process.env.GEOAPIFY_API_KEY || ''}',

  COMPANY_NAME:    '${process.env.COMPANY_NAME    || 'Choice Properties'}',
  COMPANY_EMAIL:   '${process.env.COMPANY_EMAIL   || ''}',
  COMPANY_PHONE:   '${process.env.COMPANY_PHONE   || ''}',
  COMPANY_TAGLINE: '${process.env.COMPANY_TAGLINE || 'Your trust is our standard.'}',
  COMPANY_ADDRESS: '${process.env.COMPANY_ADDRESS || ''}',

  ADMIN_EMAILS: ${JSON.stringify((process.env.ADMIN_EMAILS || '').split(',').map(e => e.trim()).filter(Boolean))},

  LEASE_DEFAULT_LATE_FEE_FLAT:  ${Number(process.env.LEASE_DEFAULT_LATE_FEE_FLAT)  || 50},
  LEASE_DEFAULT_LATE_FEE_DAILY: ${Number(process.env.LEASE_DEFAULT_LATE_FEE_DAILY) || 10},
  LEASE_DEFAULT_EXPIRY_DAYS:    ${Number(process.env.LEASE_DEFAULT_EXPIRY_DAYS)    || 7},

  FEATURES: {
    CO_APPLICANT:     ${process.env.FEATURE_CO_APPLICANT     !== 'false'},
    VEHICLE_INFO:     ${process.env.FEATURE_VEHICLE_INFO     !== 'false'},
    DOCUMENT_UPLOAD:  ${process.env.FEATURE_DOCUMENT_UPLOAD  !== 'false'},
    MESSAGING:        ${process.env.FEATURE_MESSAGING        !== 'false'},
    REALTIME_UPDATES: ${process.env.FEATURE_REALTIME_UPDATES !== 'false'},
  },
};

CONFIG.isLocalhost = ['localhost', '127.0.0.1'].includes(location.hostname);
CONFIG.baseUrl     = location.origin;

CONFIG.img = function(url, preset) {
  const fallback = url || '/assets/placeholder-property.jpg';
  if (!url) return '/assets/placeholder-property.jpg';
  if (!CONFIG.IMAGEKIT_URL || CONFIG.IMAGEKIT_URL === '') return fallback;
  const transforms = {
    card:       'tr:w-600,q-80,f-webp',
    gallery:    'tr:w-1200,q-90,f-webp',
    gallery_2x: 'tr:w-2400,q-85,f-webp',
    strip:      'tr:w-240,h-160,c-maintain_ratio,q-80,f-webp',
    thumb:      'tr:w-120,h-120,c-maintain_ratio,q-75,f-webp',
    lightbox:   'tr:q-95,f-webp',
    og:         'tr:w-1200,h-630,c-force,fo-center,q-85,f-webp',
    avatar:     'tr:w-80,h-80,c-force,fo-face,q-80,f-webp',
    avatar_lg:  'tr:w-160,h-160,c-force,fo-face,q-85,f-webp',
  };
  const tr = transforms[preset] || transforms.gallery;
  if (url.startsWith(CONFIG.IMAGEKIT_URL)) {
    const clean = url.replace(/\\/tr:[^/]+/, '');
    return clean.replace(CONFIG.IMAGEKIT_URL, CONFIG.IMAGEKIT_URL + '/' + tr);
  }
  // External URLs (Zillow, S3, etc.) — serve directly, ImageKit can't proxy them
  return url;
};

Object.freeze(CONFIG.FEATURES);
`;

fs.writeFileSync(path.join(__dirname, 'config.js'), configJs);
console.log('✓ config.js generated from environment secrets');
if (!SUPABASE_URL)      console.warn('⚠  SUPABASE_URL is not set');
if (!SUPABASE_ANON_KEY) console.warn('⚠  SUPABASE_ANON_KEY is not set');

// ── MIME types ────────────────────────────────────────────
const MIME = {
  '.html': 'text/html',
  '.css':  'text/css',
  '.js':   'application/javascript',
  '.json': 'application/json',
  '.svg':  'image/svg+xml',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.ico':  'image/x-icon',
  '.txt':  'text/plain',
  '.xml':  'application/xml',
  '.woff': 'font/woff',
  '.woff2':'font/woff2',
  '.ttf':  'font/ttf',
};

// Extensions whose responses benefit from gzip compression
const COMPRESSIBLE = new Set(['.html', '.css', '.js', '.json', '.svg', '.xml', '.txt']);

// Cache-Control policy:
//   config.js and HTML files — always revalidate (content changes without a version bump)
//   CSS / JS               — 1 hour  (versioned via ?v= param in HTML <link>/<script> tags)
//   Images / fonts         — 7 days / 30 days respectively (rarely change)
function getCacheControl(ext, urlPath) {
  if (urlPath === '/config.js') return 'no-cache, must-revalidate';
  if (ext === '.html')          return 'no-cache, must-revalidate';
  if (ext === '.css' || ext === '.js')  return 'public, max-age=3600';
  if (['.png', '.jpg', '.jpeg', '.webp', '.ico'].includes(ext)) return 'public, max-age=604800';
  if (['.woff', '.woff2', '.ttf'].includes(ext)) return 'public, max-age=2592000';
  return 'public, max-age=3600';
}

const PORT    = process.env.PORT || 5000;
const ROOT    = __dirname;

const server = http.createServer((req, res) => {
  let urlPath = req.url.split('?')[0];

  // Default to index.html for root
  if (urlPath === '/') urlPath = '/index.html';

  let filePath = path.join(ROOT, urlPath);

  // Security: prevent directory traversal
  if (!filePath.startsWith(ROOT)) {
    res.writeHead(403); res.end('Forbidden'); return;
  }

  // Try the path as-is, then with .html, then 404.html
  const candidates = [filePath, filePath + '.html', path.join(ROOT, '404.html')];

  for (const candidate of candidates) {
    if (fs.existsSync(candidate) && fs.statSync(candidate).isFile()) {
      const ext  = path.extname(candidate).toLowerCase();
      const mime = MIME[ext] || 'application/octet-stream';
      const code = candidate.endsWith('404.html') && candidate !== filePath ? 404 : 200;

      const cacheControl   = getCacheControl(ext, urlPath);
      const acceptEncoding = req.headers['accept-encoding'] || '';
      const useGzip        = COMPRESSIBLE.has(ext) && acceptEncoding.includes('gzip');

      const headers = {
        'Content-Type':  mime,
        'Cache-Control': cacheControl,
        'Vary':          'Accept-Encoding',
        'X-Content-Type-Options': 'nosniff',
        'X-Frame-Options': 'SAMEORIGIN',
        'Referrer-Policy': 'strict-origin-when-cross-origin',
        'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
        'Permissions-Policy': 'camera=(), microphone=(), geolocation=(self), payment=()',
        'Content-Security-Policy': "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com https://unpkg.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com https://unpkg.com; img-src 'self' data: https://ik.imagekit.io https://*.supabase.co https://tile.openstreetmap.org https://*.basemaps.cartocdn.com https://*.zillowstatic.com https://*.amazonaws.com https://*.cloudfront.net https://*.imgix.net https://images.unsplash.com https://*.googleusercontent.com; connect-src 'self' https://*.supabase.co https://*.supabase.in wss://*.supabase.co https://script.google.com https://api.ipify.org https://api.my-ip.io https://ipapi.co https://nominatim.openstreetmap.org https://api.geoapify.com; frame-src https://maps.google.com https://www.google.com; object-src 'none'; base-uri 'self';",
      };

      // For HTML files: inject mobile.css before </head> if not already present
      if (ext === '.html') {
        let html = fs.readFileSync(candidate, 'utf8');
        if (!html.includes('/css/mobile.css')) {
          html = html.replace(
            /<\/head>/i,
            '  <link rel="stylesheet" href="/css/mobile.css?v=4">\n</head>'
          );
        }
        const buf = Buffer.from(html, 'utf8');
        if (useGzip) {
          headers['Content-Encoding'] = 'gzip';
          res.writeHead(code, headers);
          zlib.gzip(buf, (err, compressed) => {
            res.end(err ? buf : compressed);
          });
        } else {
          headers['Content-Length'] = buf.length;
          res.writeHead(code, headers);
          res.end(buf);
        }
        return;
      }

      if (useGzip) {
        headers['Content-Encoding'] = 'gzip';
        res.writeHead(code, headers);
        fs.createReadStream(candidate).pipe(zlib.createGzip()).pipe(res);
      } else {
        res.writeHead(code, headers);
        fs.createReadStream(candidate).pipe(res);
      }
      return;
    }
  }

  res.writeHead(404); res.end('Not found');
});

server.listen(PORT, '0.0.0.0', () => {
  console.log(`✓ Choice Properties serving on http://0.0.0.0:${PORT}`);
});
